name: build-ci
on: [push, pull_request]
jobs:
  

  build-windows:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Dotnet Core 3.1 Install
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - name: Fetch Code
        uses: actions/checkout@v2
      - name: Platform build win-x64
        run: dotnet publish -c ReleaseWindows -o artifacts -r win-x64
      - name: Run InferCsharp
        uses: microsoft/infersharpaction@v1.2.1
        id: runinfersharp
        with:
          binary-path: artifacts
      - name: Upload InferCsharp report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-report
          path: infer-out/report.txt
       

  build-linux:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Dotnet Core 3.1 Install
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - name: Fetch Code
        uses: actions/checkout@v2
      - name: Platform build linux-x64
        run: |
          dotnet restore
          dotnet publish -c ReleaseLinux -o artifacts -r linux-x64
      - name: Run InferCsharp
        uses: microsoft/infersharpaction@v1.2.1
        id: runinfersharp
        with:
          binary-path: artifacts
      - name: Upload InferCsharp report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-report
          path: infer-out/report.txt
      

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dotnet Core 3.1 Install
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - name: Fetch Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: dotnet test --verbosity q
              
              
            
