name: build-ci
on: push
jobs:

   dump:
    runs-on: ubuntu-latest
    steps:
      - run: set   

  fetch-code:
    uses: ./.github/workflows/cache-code.yml
    

  build-windows:
    uses: ./.github/workflows/build.yml
    needs: [fetch-code]
    name: Windows x64 Platform Build
    with:
      version: 1.3.3
      platform: win-x64
      configuration: ReleaseWindows

  verify-windows:
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - name: Fetch Build Artifacts from Cache
        uses: actions/cache@v2
        with:
          path: ./win-x64
          key: ${{ env.GITHUB_SHA }}-win-x64
          restore-keys: ${{ env.GITHUB_SHA }}-win-x64
    
      - name: Dump Environment
        run: |
          set
          pwd
          ls -l win-x64
              
              
            
