name: build-ci
on: push
jobs:
    example:
        runs-on: mcr.microsoft.com/dotnet/sdk:3.1
        steps:
            - name: Dump Environment
              run: |
                pwd
                set
                ls -l
              
              
            
