name: build-ci
on: push
jobs:
    example:
        runs-on: ubuntu-latest
        steps:
            - name: Dump Environment
              run: |
                pwd
                set
                ls -l
              
              
            
