name: build-ci
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          pwd
          ls -laR .github
          

  build-windows:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - uses: ./.github/workflows/build/action.yml
        with:
          version: 1.3.3
          platform: win-x64
          configuration: ReleaseWindows

  verify:
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - name: Dump Environment
        run: |
          set
          pwd
          ls -l
              
              
            
