name: build-prerelease
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x.x'
        required: true
        type: string
      
jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - run: set
      - name: Create version tag
        run: echo ::set-output name=tag::$INPUTS_VERSION-$GITHUB_RUN_ID-prerelease
        id: set-tag
      - name: Tag repo ${{ steps.set-tag.outputs.tag }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.set-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

  
  
  
