name: build-ci
on: [push,pull_request]
jobs:
  

  build-windows:
    uses: ./.github/workflows/build.yml
    name: Windows x64 Platform Build
    with:
      version: 0.0.0.0
      platform: win-x64
      configuration: ReleaseWindows

  build-linux:
    uses: ./.github/workflows/build.yml
    name: Linux x64 Platform Build
    with:
      version: 0.0.0.0
      platform: linux-x64
      configuration: ReleaseLinux

  verify:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    steps:
      - name: Dump Environment
        run: |
          set
              
              
            
