name: build-ci
on: [push, pull_request]
jobs:
  

  build-windows-no-package:
    runs-on: ubuntu-latest
    if: github.event_name != "pull_request"
    steps:
      - name: Dotnet Core 3.1 Install
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - name: Fetch Code
        uses: actions/checkout@v2
        with:
          path: ./code
      - name: Platform build win-x64
        run: |
          pushd code
          dotnet publish -c ReleaseWindows -o ../build -r win-x64
          popd

  build-linux-no-package:
    runs-on: ubuntu-latest
    if: github.event_name != "pull_request"
    steps:
      - name: Dotnet Core 3.1 Install
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - name: Fetch Code
        uses: actions/checkout@v2
        with:
          path: ./code
      - name: Platform build linux-x64
        run: |
          pushd code
          dotnet publish -c ReleaseLinux -o ../build -r linux-x64
          popd
      

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dotnet Core 3.1 Install
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - name: Fetch Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: dotnet test --verbosity q
              
              
            
