name: build-prerelease
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x.x'
        required: true
        type: string
      
jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Create tag
        run: echo ::set-output name=tag::${{ github.event.inputs.version }}-$GITHUB_RUN_NUMBER-prerelease
        id: create-tag
      - name: Tag repo v${{ steps.create-tag.outputs.tag }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ steps.set-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

  
  
  
