name: build-prerelease
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x.x'
        required: true
        type: string
      
jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      packages: write
    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}
    steps:
      - name: Create tag
        run: echo ::set-output name=tag::${{ github.event.inputs.version }}-$GITHUB_RUN_NUMBER-prerelease
        id: create-tag
      - name: Tag repo v${{ steps.create-tag.outputs.tag }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ steps.create-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  un-tag-on-failure:
    runs-on: ubuntu-latest
    if: always() && ${{ needs.publish-prerelease.outputs.status }} == 'failure'
    needs: [create-tag, publish-prerelease]
    steps:
      - name: Fetch Code
        uses: actions/checkout@v2
      - name: Remove Prerelease Tag
        run: git push origin ':refs/tags/${{ needs.create-tag.outputs.tag }}'
  
      
  publish-prerelease:
    uses: ./.github/workflows/publish-build.yml
    outputs:
      status: ${{ job.status }}
    with:
      tag: ${{ needs.create-tag.outputs.tag }}
      prerelease: true
    needs: [create-tag]
      
    
  
  
  
