name: build-prerelease
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x.x'
        required: true
        type: string
      
jobs:
  set-version-tag-variable:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - run: set
      - run: ${{ inputs.version }}
      - run: export VERSION_TAG=${{ inputs.version }}
      
  
  perform-build:
    runs-on: ubuntu-latest
    needs: [set-version-tag-variable]
    steps:
      - run: set

  
  
  
