name: build-ci
on: [push]
jobs:
  

  build-windows:
    uses: ./.github/workflows/build.yml
    name: Windows x64 Platform Build
    with:
      version: 0.0.0.0
      platform: win-x64
      configuration: ReleaseWindows

  build-linux:
    uses: ./.github/workflows/build.yml
    name: Linux x64 Platform Build
    with:
      version: 0.0.0.0
      platform: linux-x64
      configuration: ReleaseLinux

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    name: Unit Tests
              
              
            
