name: pr-checks
on: [workflow_call]
jobs:

  pr-build-windows:
    name: Windows x64 Platform Build
    uses: ./.github/workflows/build.yml
    with:
      version: 0.0.0.0
      platform: win-x64
      configuration: ReleaseWindows
      package_name: pr-windows-test-package.zip

  pr-build-linux:
    name: Linux x64 Platform Build
    uses: ./.github/workflows/build.yml
    with:
      version: 0.0.0.0
      platform: linux-x64
      configuration: ReleaseLinux
      package_name: pr-linux-test-package.zip

  pr-unit-test:
    uses: ./.github/workflows/unit-test.yml
    name: Unit Tests

  infercsharp-windows:
    name: InferSharp report
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Windows Archive
        uses: actions/download-artifact@v2
        with:
          name: pr-windows-test-package.zip
          
      - name: Unzip Windows Archive
        run: unzip pr-windows-test-package.zip 
      
      - name: Run InferCsharp
        uses: microsoft/infersharpaction@v1.2.1
        id: runinfersharp
        with:
          binary-path: .

      - name: Upload InferCsharp report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-report
          path: infer-out/report.txt
  
    


  
            
