name: publish-build
on: 
  workflow_call:
    inputs:
      tag:
        description: 'The version tag to use for stamping build artifacts and naming generated archives'
        required: true
        type: string
      prerelease:
        description: 'Set to true if published build is a prerelease'
        type: boolean
        required: true
    secrets:
      PACKAGE_USER:
        required: true
      PACKAGE_PAT:
        required: true
     
        
jobs:

  build-packages:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/cxanalytix/cxanalytix
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1          

        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGE_USER }}
          password: ${{ secrets.PACKAGE_PAT }}

      - name: Dotnet Core Install
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.*
         
          
      - name: Fetch Code @ tag v${{ inputs.tag }}
        uses: actions/checkout@v2
        with:
          ref: refs/tags/v${{ inputs.tag }}

      - name: Platform build win-x64
        run: dotnet publish --self-contained -p:Version=${{ inputs.tag }}  -c ReleaseWindows -o artifacts/win-x64 -r win-x64
      - name: Platform build linux-x64
        run: dotnet publish --self-contained -p:Version=${{ inputs.tag }}  -c ReleaseLinux -o artifacts/linux-x64 -r linux-x64
      
      - name: Make win-x64 package
        run: |
          pushd artifacts/win-x64
          zip ../CxAnalytix-v${{ inputs.tag }}-win-x64.zip *
          popd
      - name: Make linux-x64 package
        run: |
          pushd artifacts/linux-x64
          zip ../CxAnalytix-v${{ inputs.tag }}-linux-x64.zip *
          popd
          
      - name: Build and Push Docker Image
        run: |
          docker build -f Dockerfile -t $DOCKER_REPO:v${{ inputs.tag }} artifacts/linux-x64
          [ ${{ inputs.prerelease }} = false ] && docker tag $DOCKER_REPO:v${{ inputs.tag }} $DOCKER_REPO:latest || :
          docker push $DOCKER_REPO:v${{ inputs.tag }}
          [ ${{ inputs.prerelease }} = false ] && docker push $DOCKER_REPO:latest || :
          

      - name: Generate publication notes
        run: |
          echo CxAnalytix v${{ inputs.tag }}\<P\> > release.md
          pushd artifacts
          sha256sum --tag $(ls *win-x64.zip) >> ../release.md
          sha256sum --tag $(ls *linux-x64.zip) >> ../release.md
          popd
          echo \<P\> >> release.md
          echo docker pull $DOCKER_REPO:v${{ inputs.tag }} >> release.md

      - name: Edit manual's version stamp
        run: echo ${{ inputs.tag }} > manual/version.tex

      - name: Build PDF Manual
        uses: xu-cheng/latex-action@v2
        with:
          root_file: manual/cxanalytix.tex
          work_in_root_file_dir: true

      - name: Build PDF Release Notes
        uses: xu-cheng/latex-action@v2
        with:
          root_file: release_notes/release_notes.tex
          work_in_root_file_dir: true
      
      - name: Move documentation artifacts
        run: |
          mv manual/cxanalytix.pdf artifacts/CxAnalytix_Manual_${{ inputs.tag }}.pdf
          mv release_notes/release_notes.pdf artifacts/CxAnalytix_ReleaseNotes_${{ inputs.tag }}.pdf


      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: artifacts/*.zip
          artifactContentType: application/zip
          bodyFile: release.md
          name: v${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          replacesArtifacts: true
          tag: v${{ inputs.tag }}
          
      - name: Update Documentation for GitHub Release
        id: update_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: artifacts/*.pdf
          artifactContentType: application/pdf
          omitBodyDuringUpdate: true
          name: v${{ inputs.tag }}
          omitNameDuringUpdate: true
          prerelease: ${{ inputs.prerelease }}
          replacesArtifacts: false
          removeArtifacts: false
          tag: v${{ inputs.tag }}
          
          

      
          


        
        
        
