name: unit-test
on: workflow_call

jobs:
  exec-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dotnet Core 3.1 Install
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - name: Fetch Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: dotnet test --verbosity q
              
            
